### ISSUE TITLE
BUG: Crash when starting recording (caused by aac)

### ISSUE THREAD

**Issue by Segergren** [lulzsun/RePlays#102]
My RePlays crashes on 1.2.0.

[2023-04-09 20:50:30][DetectionService.cs(305)]: Process [19804][valheim.exe]: Got MainWindow [Valheim]
[2023-04-09 20:50:30][DetectionService.cs(314)]: This process [19804] is a recordable game [valheim.exe], prepared to record
[2023-04-09 20:50:30][DetectionService.cs(318)]: Is allowed to record: True
[2023-04-09 20:50:30][RecordingService.cs(60)]: Is PreRecording False
[2023-04-09 20:50:30][RecordingService.cs(61)]: Is Recording False
[2023-04-09 20:50:30][LibObsRecorder.cs(190)]: Game capture window size: 2560x1440
[2023-04-09 20:50:30][LibObsRecorder.cs(70)]: warning: 1 views remain at shutdown
[2023-04-09 20:50:30][LibObsRecorder.cs(70)]: info: ---------------------------------
[2023-04-09 20:50:30][DetectionService.cs(300)]: Process [60044][UnityCrashHandler64.exe]: Got no MainWindow. Retrying... 1/40
[2023-04-09 20:50:30][LibObsRecorder.cs(70)]: info: video settings reset:
	base resolution:   2560x1440
	output resolution: 2560x1440
	downscale filter:  Bilinear
	fps:               60/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
[2023-04-09 20:50:30][LibObsRecorder.cs(70)]: info: NV12 texture support enabled
[2023-04-09 20:50:30][LibObsRecorder.cs(70)]: info: P010 texture support not available
[2023-04-09 20:50:30][LibObsRecorder.cs(194)]: Preparing to create libobs output [4897]...
[2023-04-09 20:50:30][LibObsRecorder.cs(70)]: info: [win-wasapi: 'output_Speakers (Logitech PRO X Wireless Gaming Headset)'] update settings:
	device id: {0.0.0.00000000}.{dec55070-a2ee-4602-b3d5-041fb4dde286}
	use device timing: 1
[2023-04-09 20:50:30][LibObsRecorder.cs(70)]: debug: source 'output_Speakers (Logitech PRO X Wireless Gaming Headset)' (wasapi_output_capture) created
[2023-04-09 20:50:30][LibObsRecorder.cs(70)]: debug: encoder 'aac0' (ffmpeg_aac) created

> [2023-04-09 20:50:30][External Library(0)]: System.Collections.Generic.KeyNotFoundException: The given key 'aac5' was not present in the dictionary.
>    at System.Collections.Generic.Dictionary2.get_Item(TKey key)
>    at RePlays.Recorders.LibObsRecorder.StartRecording() in D:\Documents\GitHub\RePlays\Classes\Recorders\LibObsRecorder.cs:line 211
>    at RePlays.Services.RecordingService.StartRecording() in D:\Documents\GitHub\RePlays\Classes\Services\RecordingService.cs:line 66
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

[2023-04-09 20:50:30][LibObsRecorder.cs(70)]: info: WASAPI: Device 'Speakers (Logitech PRO X Wireless Gaming Headset)' [44100 Hz] initialized
> "**Crashes**"

**These are my audio settings**
    "inputDevicesCache": [
      {
        "deviceId": "default",
        "deviceLabel": "Default Device",
        "deviceVolume": 100
      },
      {
        "deviceId": "communications",
        "deviceLabel": "Default Communication Device",
        "deviceVolume": 100
      },
      {
        "deviceId": "{0.0.1.00000000}.{a1b17db2-83c6-4d38-a240-746a03c0a88d}",
        "deviceLabel": "Microphone (3- Shure MV7)",
        "deviceVolume": 100
      },
      {
        "deviceId": "{0.0.1.00000000}.{15584581-e462-4aed-8546-e2f4175e9d04}",
        "deviceLabel": "Microphone (Logitech PRO X Wireless Gaming Headset)",
        "deviceVolume": 100
      }
    ],
    "inputDevices": [
      {
        "deviceId": "{0.0.1.00000000}.{a1b17db2-83c6-4d38-a240-746a03c0a88d}",
        "deviceLabel": "Microphone (3- Shure MV7)",
        "deviceVolume": 100
      }
    ],
    "outputDevicesCache": [
      {
        "deviceId": "default",
        "deviceLabel": "Default Device",
        "deviceVolume": 100
      },
      {
        "deviceId": "communications",
        "deviceLabel": "Default Communication Device",
        "deviceVolume": 100
      },
      {
        "deviceId": "{0.0.0.00000000}.{dec55070-a2ee-4602-b3d5-041fb4dde286}",
        "deviceLabel": "Speakers (Logitech PRO X Wireless Gaming Headset)",
        "deviceVolume": 100
      },
      {
        "deviceId": "{0.0.0.00000000}.{069a511d-1917-45cf-b135-c978e3ef0fa0}",
        "deviceLabel": "Speakers (Realtek(R) Audio)",
        "deviceVolume": 100
      }
    ],
    "outputDevices": [
      {
        "deviceId": "{0.0.0.00000000}.{dec55070-a2ee-4602-b3d5-041fb4dde286}",
        "deviceLabel": "Speakers (Logitech PRO X Wireless Gaming Headset)",
        "deviceVolume": 100
      }
    ]

**Comment by lulzsun** [comment]
Fixed in 1.2.1 release.
