### ISSUE TITLE
Unhandled exception when game has a comma in the title

### ISSUE THREAD

**Issue by HotshotGT** [lulzsun/RePlays#251]
Just trying out the program for the first time and found that I couldn't save clips of Darktide. Screenshot and contents of the error dialog are below, but it seems related to the comma in "40,000" as everything worked fine once I set the name "Darktide" via the detection menu.

![image](https://github.com/user-attachments/assets/30e398a6-9e91-4743-b1ff-314692ad5fc5)

<details>
<summary>Exception message</summary>

```
See the end of this message for details on invoking just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Gameplay\Warhammer 40%2C000 Darktide\2024_11_14_02_53_59-clp.mp4'.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at RePlays.Utils.Functions.CreateClip(String game, String videoPath, ClipSegment[] clipSegments, Int32 index, Int32 progress, String uuid) in D:\a\RePlays\RePlays\Classes\Utils\Helpers.cs:line 585
   at RePlays.Utils.WebMessage.<>c__DisplayClass16_1.<ReceiveMessage>b__3() in D:\a\RePlays\RePlays\Classes\Utils\Messages.cs:line 344
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at RePlays.Utils.WebMessage.ReceiveMessage(String message) in D:\a\RePlays\RePlays\Classes\Utils\Messages.cs:line 344
   at RePlays.WindowsInterface.WebMessageReceivedAsync(Object sender, CoreWebView2WebMessageReceivedEventArgs e) in D:\a\RePlays\RePlays\Classes\WindowsInterface.cs:line 154
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Private.CoreLib.dll
----------------------------------------
RePlays
    Assembly Version: 0.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\RePlays.dll
----------------------------------------
System.Runtime
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Runtime.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Net.Sockets.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Net.Primitives.dll
----------------------------------------
System.Linq
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Linq.dll
----------------------------------------
System.Threading
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Threading.dll
----------------------------------------
SquirrelLib
    Assembly Version: 2.11.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\SquirrelLib.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Collections.Specialized.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Diagnostics.Process.dll
----------------------------------------
System.Collections
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Collections.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Runtime.InteropServices.dll
----------------------------------------
System.Console
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Console.dll
----------------------------------------
System.Text.Json
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Text.Json.dll
----------------------------------------
System.Memory
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Memory.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Text.Encoding.Extensions.dll
----------------------------------------
System.Text.Encodings.Web
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Runtime.Intrinsics.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Numerics.Vectors.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Private.Uri.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Collections.Concurrent.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Collections.NonGeneric.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\Microsoft.Win32.Primitives.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Text.RegularExpressions.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.IO.Compression.dll
----------------------------------------
System.Xml.XDocument
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Xml.XDocument.dll
----------------------------------------
System.Private.Xml.Linq
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Private.Xml.Linq.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Private.Xml.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Xml.ReaderWriter.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Threading.Thread.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Security.Cryptography.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Management
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Management.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\Microsoft.Win32.Registry.dll
----------------------------------------
System.IO.FileSystem.DriveInfo
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.IO.FileSystem.DriveInfo.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.2420.47
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\Microsoft.Web.WebView2.WinForms.dll
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 1.0.2420.47
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\Microsoft.Web.WebView2.Core.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\mscorlib.dll
----------------------------------------
SharpHook
    Assembly Version: 5.3.1.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\SharpHook.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Net.Http
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Net.Http.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Diagnostics.Tracing.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Net.Security.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Diagnostics.TraceSource.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Threading.ThreadPool.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.ComponentModel.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Runtime.Loader.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Security.Claims.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Linq.Expressions.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Location: 
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Net.WebSockets
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Net.WebSockets.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Threading.Tasks.dll
----------------------------------------
System.Drawing
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Drawing.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Runtime.Extensions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Runtime.Numerics.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Windows.Extensions.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 8.0.0.0
    Location: C:\Users\Hotshot\AppData\Local\RePlays\app-1.3.44\System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************```

</details>

**Comment by lulzsun** [comment]
https://github.com/lulzsun/RePlays/commit/ebfc8c68e7844a5cbd6e72c0a3289c5e4a4ca815 should fix the issue in the next nightly release (v1.3.45+).
