### ISSUE TITLE
Auto closing after recording

### ISSUE THREAD

**Issue by Vusker** [lulzsun/RePlays#257]
Yo,

app is automatically closing after it records once and i have to manually launch it to record again. After that it happens again.

Version 1.3.47

**Comment by lulzsun** [comment]
I noticed this issue just now, it seems that when stopping the recording of games that have game integration (i.e, League of Legends), it will crash when creating the metadata.

```
[11/28/2024 3:18:43 AM][v1.3.47][External Library::WorkerThreadStart(0)]: System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at RePlays.Utils.Functions.GetOrCreateMetadata(String videoPath) in D:\a\RePlays\RePlays\Classes\Utils\Helpers.cs:line 416
   at RePlays.Recorders.LibObsRecorder.StopRecording() in D:\a\RePlays\RePlays\Classes\Recorders\LibObsRecorder.cs:line 752
   at RePlays.Services.RecordingService.StopRecording(Boolean user) in D:\a\RePlays\RePlays\Classes\Services\RecordingService.cs:line 168
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

Must be an issue related to our recent refactor, will look into it soon.

**Comment by Segergren** [comment]
I've also noticed this: https://discord.com/channels/654698116917886986/654699568528621570/1311092964923146350 :(

**Comment by sonicv6** [comment]
My bad, I'll look into this when I get home. Should be limited to League Of Legends.

**Comment by Segergren** [comment]
It's not. I have no bookmarks in CS2

**Comment by sonicv6** [comment]
Okay, I'll look into that too

**Comment by lulzsun** [comment]
The issue seems to be that sometimes `RecordingService.GetCurrentSession().videoSavePath` is null or empty. Not sure why since sometimes the path is returned just fine:

```
[11/28/2024 3:18:43 AM][v1.3.47][LibObsRecorder.cs::StopRecording(747)]: Session recording saved to 
...
[11/27/2024 3:18:48 AM][v1.3.47][LibObsRecorder.cs::StopRecording(747)]: Session recording saved to F:/Videos/Plays/Dead by Daylight/2024_11_27_02_55_41-ses.mkv
```

Also, It might not specifically be a game integration related issue. `videoSavePath` also went null when playing Deadlock.

**Comment by sonicv6** [comment]
Okay, that's strange. All I did was move where that is assigned, but it should always get assigned, I didn't change the logic at all.

**Comment by lulzsun** [comment]
Closing issue as this was fixed in https://github.com/lulzsun/RePlays/commit/ea4ae73955e95f7227a12e6ba4b87bcbf4be8909
